name: Bug Report
description: Create a report to help us improve
labels: ["bug"]
body:
- type: textarea      
  attributes:
    label: Describe the issue
    description: A clear and concise description of what the bug is.
  validations:
    required: true

- type: dropdown
  id: nameless_version
  attributes:
    label: NamelessMC Version
    description: From StaffCP -> Overview
    options:
      - 2.0.0-pr12
      - <= 2.0.0-pr11
      - 1.0.21
      - <= 1.0.20
  validations:
    required: true

- type: dropdown
  id: nexus_version
  attributes:
    label: Nexus Version
    description: From StaffCP -> Nexus -> Updates
    options:
      - 1.5.0
      - <= 1.4.0
  validations:
    required: true

- type: textarea      
  attributes:
    label: To Reproduce
    description: "Steps to reproduce the behaviour."
    placeholder: "1. Go to '...'

     2. Click on '....'

     3. Scroll down to '.....'

     4. See error"
  validations:
    required: true

- type: textarea      
  attributes:
    label: Expected Behaviour
    description: What were you expecting to happen?
  validations:
    required: true

- type: textarea      
  attributes:
    label: Desktop
    description: Please complete the following information.
  validations:
    required: false
  value: |
    - OS: [e.g. Windows]
    - Browser [e.g. chrome, safari]
    - Version [e.g. 22]
